api/urls.py
from django.urls import path, include
from .views import *
from newsapp.models import *
from rest_framework import routers




router = routers.DefaultRouter()


router.register('tag', TagAPIView)
router.register('category', CategoryAPIView)
router.register('topic', TopicAPIView)
router.register('news', NewsAPIView)





urlpatterns = [
   path('', include(router.urls)),
]

newsapp/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'newsapp'


urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('<int:pk>/detail/', ClientPostDetailView.as_view(), name='clientnewsdetail'),
    path('posts/topic/<int:pk>/', ClientPostTopic.as_view(), name='clientnewstopic'),
    path('posts/tag/<int:pk>/', ClientPostTag.as_view(), name='clientnewstag'),
    path('posts/category/<int:pk>/', ClientPostCategory.as_view(), name='clientnewscategory'),
    
    



    # CLIENT URL PATTERNS

    # path('', ClientHomeView.as_view(), name="clienthome"),
    # path('blogs/', ClientDemoView.as_view(), name="clientbloglist"),



    # ADMIN URL PATTERNS


    #  ADMIN AUTHENTICATION
    path('admin-login/', auth_views.LoginView.as_view(template_name='admintemplates/adminlogin.html'), name='adminlogin'),
    path('admin-logout/', auth_views.LogoutView.as_view(template_name='admintemplates/adminlogout.html'), name='adminlogout'),

    # ADMIN:NEWS CRUD
    path('admin-panel/news/',
         AdminNewsListView.as_view(),
         name='adminnewslist'),
    path('admin-panel/news/<int:pk>/detail/',
         AdminNewsDetailView.as_view(),
         name='adminnewsdetail'),
    path('admin-panel/news/create/',
         AdminNewsCreateView.as_view(),
         name='adminnewscreate'),
    path('admin-panel/news/<int:pk>/update/',
         AdminNewsUpdateView.as_view(),
         name='adminnewsupdate'),
    path('admin-panel/news/<int:pk>/delete/',
         AdminNewsDeleteView.as_view(),
         name='adminnewsdelete'),





    # path('album/create/', AdminGalleryCreateView.as_view(), name='adminalbumcreate'),
    

    path('album/create/', AdminGalleryView.as_view(), name='adminalbumcreate'),
#     path('album/delete/<int:pk>', AdminImageDeleteView.as_view(), name='adminalbumdelete'),
    path('album/delete/<int:pk>', adminDeleteImage, name='adminalbumdelete'),

    # path('album/<int:pk>/', AdminAlbumDetailView.as_view(), name='adminalbumlist'),


    # path('admin-panel/blog/create/',
    #      BlogCreateView.as_view(),
    #      name='adminblogcreate'),
    # path('admin-panel/blog/<int:pk>/update/',
    #      BlogUpdateView.as_view(),
    #      name='adminblogupdate'),
    # path('admin-panel/blog/<int:pk>/delete/',
    #      BlogDeleteView.as_view(),
    #      name='adminblogdelete'),

]

newsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from newsapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('summernote/', include('django_summernote.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/clientbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>{% block title %} {% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Favicon -->
    <link rel="icon" href="{% static 'clientstatic/img/core-img/favicon.ico' %}">

    <!-- Core Stylesheet -->
    <link href="{% static 'clientstatic/style.css' %}" rel="stylesheet">

    <!-- Responsive CSS -->
    <link href="{% static 'clientstatic/css/responsive/responsive.css' %}" rel="stylesheet">

</head>

<body>
    <!-- Preloader Start -->
    <div id="preloader">
        <div class="yummy-load"></div>
    </div>

    <!-- Background Pattern Swither -->
    <div id="pattern-switcher">
        Bg Pattern
    </div>
    <div id="patter-close">
        <i class="fa fa-times" aria-hidden="true"></i>
    </div>

    {% include 'clienttemplates/clienttopheader.html' %}

    {% include 'clienttemplates/clientheader.html' %}





    {% block content %}

    {% endblock %}




    {% include 'clienttemplates/clientsocial.html' %}



    <!-- Jquery-2.2.4 js -->
    <script src="{% static 'clientstatic/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'clientstatic/js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap-4 js -->
    <script src="{% static 'clientstatic/js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins JS -->
    <script src="{% static 'clientstatic/js/others/plugins.js' %}"></script>
    <!-- Active JS -->
    <script src="{% static 'clientstatic/js/active.js' %}"></script>


</body>

templates/clienttemplates/clientfooter.html
<!-- ****** Footer Menu Area Start ****** -->
<footer class="footer_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="footer-content">
                    <!-- Logo Area Start -->
                    <div class="footer-logo-area text-center">
                        <a href="index.html" class="yummy-logo">Yummy Blog</a>
                    </div>
                    <!-- Menu Area Start -->
                    <nav class="navbar navbar-expand-lg">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#yummyfood-footer-nav" aria-controls="yummyfood-footer-nav" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars" aria-hidden="true"></i> Menu</button>
                        <!-- Menu Area Start -->
                        <div class="collapse navbar-collapse justify-content-center" id="yummyfood-footer-nav">
                            <ul class="navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Features</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Categories</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Archive</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Contact</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Copywrite Text -->
                <div class="copy_right_text text-center">
                    <p>Copyright @2018 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ****** Footer Menu Area End ****** -->

templates/clienttemplates/clientheader.html
<!-- ****** Header Area Start ****** -->
<header class="header_area">
    <div class="container">
        <div class="row">
            <!-- Logo Area Start -->
            <div class="col-12">
                <div class="logo_area text-center">
                    <a href="{% url 'newsapp:clienthome' %}" class="yummy-logo">Yummy Blog</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#yummyfood-nav" aria-controls="yummyfood-nav" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars" aria-hidden="true"></i> Menu</button>
                    <!-- Menu Area Start -->
                    <div class="collapse navbar-collapse justify-content-center" id="yummyfood-nav">
                        <ul class="navbar-nav" id="yummy-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'newsapp:clienthome' %}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="contact.html">Contact</a>
                            </li>

                            {% for c in categories %}
                                <li class="nav-item">       
                                    <a class="nav-link dropdown-toggle" href="#" id="{{ c.name }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{c.name}}</a>
                                    <div class="dropdown-menu" aria-labelledby="{{c.name}}">
                                        {% for t in c.topics.all %}
                                            {% if t.subject %}
                                                <a class="dropdown-item" href="{% url 'newsapp:clientnewstopic' t.pk %}">{{ t.subject }}</a>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                        
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ****** Header Area End ****** -->

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}


{% block content %}

<!-- ****** Categories Area Start ****** -->
<section class="categories_area clearfix" id="about">
    <div class="container">
        <div class="row">
            {% for category in categories %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="single_catagory wow fadeInUp" data-wow-delay=".3s">
                    <img src="{% static 'clientstatic/img/catagory-img/1.jpg' %}" alt="">
                    <div class="catagory-title">
                        <a href="{% url 'newsapp:clientnewscategory' category.id %}">
                            <h5>{{ category.name }}</h5>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>   
    </div>
</section>
<!-- ****** Categories Area End ****** -->

{% include 'clienttemplates/widgets/blogs.html' %}


{% endblock %}

templates/clienttemplates/clientnewscategory.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block content %}



<!-- Single Post -->
<section class="single_blog_area section_padding_80">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-lg-11">
				<div class="row no-gutters">
					<div class="col-12">
						<div class="single-post wow fadeInUp" data-wow-delay=".2s">
							<!-- Post Thumb -->
							<!-- Post Thumb -->
						<!-- 	{% for post in posts|slice:":1" %}
							<a href="#">
								<h1 class="post-headline" style="color:red;">{{ post.topic.category.name }}</h1>
								<hr>
							</a>
							{% endfor %} -->

							<a href="#">
								<h1 class="post-headline" style="color:red;">{{ cat }}</h1>
								<hr>
							</a>

							{% for post in object_list %}
							<!-- Post Content -->
							<div class="post-content">
								<div class="post-meta d-flex">
									<div class="post-author-date-area d-flex">
										<!-- Post Author -->
										<div class="post-author">
											<a href="#">@{{post.author}}</a>
										</div>
										<div class="post-author">
											<a href="{% url 'newsapp:clientnewstopic' post.topic.pk %}">{{ post.topic }} => {{post.topic.category.name}}</a>
										</div>
										<!-- Post Date -->
										<div class="post-date">
											<a href="#">{{ post.created_at }}</a>
										</div>
									</div>
									<!-- Post Comment & Share Area -->
									<div class="post-comment-share-area d-flex">
										<!-- Post Favourite -->
										<div class="post-favourite">
											<a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
										</div>
										<!-- Post Comments -->
										<div class="post-comments">
											<a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
										</div>
										<!-- Post Share -->
										<div class="post-share">
											<a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
										</div>
									</div>
								</div>
								<a href="{% url 'newsapp:clientnewsdetail' post.pk %}">
									<h2 class="post-headline">{{ post.title }}</h2>
								</a>
								<p>{{ post.content | striptags | safe | truncatechars:300 }} </p>
								<a href="{% url 'newsapp:clientnewsdetail' post.pk %}" class="read-more">Continue Reading..</a>
								<hr>
								<hr>
							</div>
							{% endfor %}

							<!-- Pagination -->
							<div class="pagination" style="margin-left:  350px;">
							    <span class="step-links">
							        {% if page_obj.has_previous %}
							            <a href="?page=1"> first</a>
							            <a href="?page={{ page_obj.previous_page_number }}"><button class="btn btn-info">&laquo; </button> </a>
							        {% endif %}

							        <span class="current">
							            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
							        </span>

							        {% if page_obj.has_next %}
							            <a href="?page={{ page_obj.next_page_number }}"><button class="btn btn-info"> &raquo; </button></a>
							            <a href="?page={{ page_obj.paginator.num_pages }}">last </a>
							        {% endif %}
							    </span>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>




{% endblock %}

templates/clienttemplates/clientnewsdetail.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}

<section class="single_blog_area section_padding_80">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-lg-11">
				<div class="row no-gutters">

					<!-- Single Post Share Info -->
					<div class="col-2 col-sm-1">
						<div class="single-post-share-info mt-100">
							<a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
							<a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
							<a href="#" class="googleplus"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
							<a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
							<a href="#" class="pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
						</div>
					</div>

					<!-- Single Post -->
					<div class="col-10 col-sm-11">
						<div class="single-post">
							<!-- Post Thumb -->
							<div class="post-thumb">
								<!-- <img src="{% static 'clienttemplatesimg/blog-img/10.jpg' %}" alt=""> -->
								{% if post.image %}
								<img src="{{ post.image.url|default_if_none:'#' }}" alt="{{ post.title }}">
								{% endif %}
							</div>
							<!-- Post Content -->
							<div class="post-content">
								<div class="post-meta d-flex">
									<div class="post-author-date-area d-flex">
										<!-- Post Author -->
										<div class="post-author">
											<a href="#">@{{ post.author }}</a>
										</div>
										<div class="post-author">
											<a href="#">Views : {{ post.post_count }}</a>
										</div>
										<!-- Post Date -->
										<div class="post-date">
											<a href="#">{{ post.created_at }}</a>
										</div>
									</div>
									<!-- Post Comment & Share Area -->
									<div class="post-comment-share-area d-flex">
										<!-- Post Favourite -->
										<div class="post-favourite">
											<a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
										</div>
										<!-- Post Comments -->
										<div class="post-comments">
											<a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
										</div>
										<!-- Post Share -->
										<div class="post-share">
											<a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
										</div>
									</div>
								</div>
								<a href="#">
									<h2 class="post-headline">{{ post.title }}</h2>
								</a>

								{{ post.content | safe }}

								<img class="br-30 mb-15" src="img/blog-img/14.jpg" alt="">

							</div>
						</div>

						<!-- Tags Area -->

						<div class="tags-area">
							{% for t in post.tag.all %}
							<a href="{% url 'newsapp:clientnewstag' t.pk %}">{{t.word}}</a>
							{% endfor %}
						</div>
						{% include 'clienttemplates/relatedpost.html' %}
					</div>
				</div>
			</div>
		</div>
	</div>
</section>


{% endblock %}

templates/clienttemplates/clientnewstag.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block content %}



<!-- Single Post -->
<section class="single_blog_area section_padding_80">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-lg-11">
				<div class="row no-gutters">
					<div class="col-12">
						<div class="single-post wow fadeInUp" data-wow-delay=".2s">
							<!-- Post Thumb -->
							<a href="{% url 'newsapp:clientnewstopic' tag.id %}">
								<h1 class="post-headline" style="color: lightblue;">#{{ tag }}</h1>
								<hr>
							</a>
							{% for post in object_list %}
							<!-- Post Content -->
							<div class="post-content">
								<div class="post-meta d-flex">
									<div class="post-author-date-area d-flex">
										<!-- Post Author -->
										<div class="post-author">
											<a href="#">@{{post.author}}</a>
										</div>
										<div class="post-author">
											<a href="{% url 'newsapp:clientnewstopic' post.topic.pk %}">{{ post.topic }}</a>
										</div>
										<!-- Post Date -->
										<div class="post-date">
											<a href="#">{{ post.created_at }}</a>
										</div>
									</div>
									<!-- Post Comment & Share Area -->
									<div class="post-comment-share-area d-flex">
										<!-- Post Favourite -->
										<div class="post-favourite">
											<a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
										</div>
										<!-- Post Comments -->
										<div class="post-comments">
											<a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
										</div>
										<!-- Post Share -->
										<div class="post-share">
											<a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
										</div>
									</div>
								</div>
								<a href="{% url 'newsapp:clientnewsdetail' post.id %}">
									<h2 class="post-headline">{{ post.title }}</h2>
								</a>
								<p>{{ post.content | striptags | safe | truncatechars:300 }} </p>
								<a href="{% url 'newsapp:clientnewsdetail' post.id %}" class="read-more">Continue Reading..</a>
								<hr>
								<hr>
							</div>
							{% endfor %}

							{% include 'clienttemplates/widgets/pagination.html' %}
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>




{% endblock %}

templates/clienttemplates/clientnewstopic.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block content %}



<!-- Single Post -->
<section class="single_blog_area section_padding_80">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-lg-11">
				<div class="row no-gutters">
					<div class="col-12">
						<div class="single-post wow fadeInUp" data-wow-delay=".2s">
							<!-- Post Thumb -->
							<a href="{% url 'newsapp:clientnewstopic' topic.id %}">
								<h1 class="post-headline" style="color: red;">{{ topic | upper }}</h1>
								<hr>
							</a>
							{% for post in object_list %}
							<!-- Post Content -->
							<div class="post-content">
								<div class="post-meta d-flex">
									<div class="post-author-date-area d-flex">
										<!-- Post Author -->
										<div class="post-author">
											<a href="#">@{{post.author}}</a>
										</div>
										<div class="post-author">
											<a href="{% url 'newsapp:clientnewstopic' post.topic.pk %}">{{ post.topic }}</a>
										</div>
										<!-- Post Date -->
										<div class="post-date">
											<a href="#">{{ post.created_at }}</a>
										</div>
									</div>
									<!-- Post Comment & Share Area -->
									<div class="post-comment-share-area d-flex">
										<!-- Post Favourite -->
										<div class="post-favourite">
											<a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
										</div>
										<!-- Post Comments -->
										<div class="post-comments">
											<a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
										</div>
										<!-- Post Share -->
										<div class="post-share">
											<a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
										</div>
									</div>
								</div>
								<a href="{% url 'newsapp:clientnewsdetail' post.id %}">
									<h2 class="post-headline">{{ post.title }}</h2>
								</a>
								<p>{{ post.content | striptags | safe | truncatechars:300 }} </p>
								<a href="{% url 'newsapp:clientnewsdetail' post.id %}" class="read-more">Continue Reading..</a>
								<hr>
								<hr>
							</div>
							{% endfor %}

							{% include 'clienttemplates/widgets/pagination.html' %}
						</div>

						

					</div>
					
					
				</div>
			</div>
		</div>
	</div>
</section>




{% endblock %}

templates/clienttemplates/clientslider.html
<!-- ****** Welcome Post Area Start ****** -->
<section class="welcome-post-sliders owl-carousel">

    <!-- Single Slide -->
    <div class="welcome-single-slide">
        <!-- Post Thumb -->
        <img src="img/bg-img/slide-1.jpg" alt="">
        <!-- Overlay Text -->
        <div class="project_title">
            <div class="post-date-commnents d-flex">
                <a href="#">May 19, 2017</a>
                <a href="#">5 Comment</a>
            </div>
            <a href="#">
                <h5>“I’ve Come and I’m Gone”: A Tribute to Istanbul’s Street</h5>
            </a>
        </div>
    </div>

    <!-- Single Slide -->
    <div class="welcome-single-slide">
        <!-- Post Thumb -->
        <img src="img/bg-img/slide-2.jpg" alt="">
        <!-- Overlay Text -->
        <div class="project_title">
            <div class="post-date-commnents d-flex">
                <a href="#">May 19, 2017</a>
                <a href="#">5 Comment</a>
            </div>
            <a href="#">
                <h5>“I’ve Come and I’m Gone”: A Tribute to Istanbul’s Street</h5>
            </a>
        </div>
    </div>

    <!-- Single Slide -->
    <div class="welcome-single-slide">
        <!-- Post Thumb -->
        <img src="img/bg-img/slide-3.jpg" alt="">
        <!-- Overlay Text -->
        <div class="project_title">
            <div class="post-date-commnents d-flex">
                <a href="#">May 19, 2017</a>
                <a href="#">5 Comment</a>
            </div>
            <a href="#">
                <h5>“I’ve Come and I’m Gone”: A Tribute to Istanbul’s Street</h5>
            </a>
        </div>
    </div>

    <!-- Single Slide -->
    <div class="welcome-single-slide">
        <!-- Post Thumb -->
        <img src="img/bg-img/slide-4.jpg" alt="">
        <!-- Overlay Text -->
        <div class="project_title">
            <div class="post-date-commnents d-flex">
                <a href="#">May 19, 2017</a>
                <a href="#">5 Comment</a>
            </div>
            <a href="#">
                <h5>“I’ve Come and I’m Gone”: A Tribute to Istanbul’s Street</h5>
            </a>
        </div>
    </div>

    <!-- Single Slide -->
    <div class="welcome-single-slide">
        <!-- Post Thumb -->
        <img src="img/bg-img/slide-4.jpg" alt="">
        <!-- Overlay Text -->
        <div class="project_title">
            <div class="post-date-commnents d-flex">
                <a href="#">May 19, 2017</a>
                <a href="#">5 Comment</a>
            </div>
            <a href="#">
                <h5>“I’ve Come and I’m Gone”: A Tribute to Istanbul’s Street</h5>
            </a>
        </div>
    </div>
</section>
<!-- ****** Welcome Area End ****** -->

templates/clienttemplates/clienttopheader.html
<!-- ****** Top Header Area Start ****** -->
<div class="top_header_area">
    <div class="container">
        <div class="row">
            <div class="col-5 col-sm-6">
                <!--  Top Social bar start -->
                <div class="top_social_bar">
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                </div>
            </div>
            <!--  Login Register Area -->
            <div class="col-7 col-sm-6">
                <div class="signup-search-area d-flex align-items-center justify-content-end">
                    <div class="login_register_area d-flex">
                        <div class="login">
                            <a href="register.html">Sing in</a>
                        </div>
                        <div class="register">
                            <a href="register.html">Sing up</a>
                        </div>
                    </div>
                    <!-- Search Button Area -->
                    <div class="search_button">
                        <a class="searchBtn" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                    </div>
                    <!-- Search Form -->
                    <div class="search-hidden-form">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search-anything" placeholder="Search Anything...">
                            <input type="submit" value="" class="d-none">
                            <span class="searchBtn"><i class="fa fa-times" aria-hidden="true"></i></span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ****** Top Header Area End ****** -->

templates/clienttemplates/order.html
    {% include 'clienttemplates/clienttopheader.html' %}

    {% include 'clienttemplates/clientheader.html' %}

    {% include 'clienttemplates/clientslider.html'%}

    {% include 'clienttemplates/clientcategories.html' %}

    {% include 'clienttemplates/clientblog.html' %}

    {% include 'clienttemplates/clientsocial.html' %}

    {% include 'clienttemplates/clientfooter.html' %}














{% include 'clienttemplates/widgets/singlepostdemo.html' %}

{% include 'clienttemplates/widgets/popularpost.html' %}

{% include 'clienttemplates/widgets/foursinglepost.html' %}

{% include 'clienttemplates/widgets/individualfour.html' %}