api/urls.py
from django.urls import path, include
from .views import *
from newsapp.models import *
from rest_framework import routers




router = routers.DefaultRouter()


router.register('tag', TagAPIView)
router.register('category', CategoryAPIView)
router.register('topic', TopicAPIView)
router.register('news', NewsAPIView)





urlpatterns = [
   path('', include(router.urls)),
]

newsapp/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'newsapp'


urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('<int:pk>/detail/', ClientPostDetailView.as_view(), name='clientnewsdetail'),
    path('posts/topic/<int:pk>/', ClientPostTopic.as_view(), name='clientnewstopic'),
    path('posts/tag/<int:pk>/', ClientPostTag.as_view(), name='clientnewstag'),
    path('posts/category/<int:pk>/', ClientPostCategory.as_view(), name='clientnewscategory'),
    
    



    # CLIENT URL PATTERNS

    # path('', ClientHomeView.as_view(), name="clienthome"),
    # path('blogs/', ClientDemoView.as_view(), name="clientbloglist"),



    # ADMIN URL PATTERNS


    #  ADMIN AUTHENTICATION
    path('admin-login/', auth_views.LoginView.as_view(template_name='admintemplates/adminlogin.html'), name='adminlogin'),
    path('admin-logout/', auth_views.LogoutView.as_view(template_name='admintemplates/adminlogout.html'), name='adminlogout'),

    # ADMIN:NEWS CRUD
    path('admin-panel/news/',
         AdminNewsListView.as_view(),
         name='adminnewslist'),
    path('admin-panel/news/<int:pk>/detail/',
         AdminNewsDetailView.as_view(),
         name='adminnewsdetail'),
    path('admin-panel/news/create/',
         AdminNewsCreateView.as_view(),
         name='adminnewscreate'),
    path('admin-panel/news/<int:pk>/update/',
         AdminNewsUpdateView.as_view(),
         name='adminnewsupdate'),
    path('admin-panel/news/<int:pk>/delete/',
         AdminNewsDeleteView.as_view(),
         name='adminnewsdelete'),





    # path('album/create/', AdminGalleryCreateView.as_view(), name='adminalbumcreate'),
    

    path('album/create/', AdminGalleryView.as_view(), name='adminalbumcreate'),
#     path('album/delete/<int:pk>', AdminImageDeleteView.as_view(), name='adminalbumdelete'),
    path('album/delete/<int:pk>', adminDeleteImage, name='adminalbumdelete'),

    # path('album/<int:pk>/', AdminAlbumDetailView.as_view(), name='adminalbumlist'),


    # path('admin-panel/blog/create/',
    #      BlogCreateView.as_view(),
    #      name='adminblogcreate'),
    # path('admin-panel/blog/<int:pk>/update/',
    #      BlogUpdateView.as_view(),
    #      name='adminblogupdate'),
    # path('admin-panel/blog/<int:pk>/delete/',
    #      BlogDeleteView.as_view(),
    #      name='adminblogdelete'),

]

newsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from newsapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('summernote/', include('django_summernote.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <!-- CSS CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'adminstatic/newsapp/css/style.css' %}" type="text/css">
</head>

<body>
  {% include 'admintemplates/navbar.html' %}

  {% block content %}

  {% endblock content %}

  <script src="{% static 'adminstatic/newsapp/js/jquery.min.js' %}"></script>
  <script src="{% static 'adminstatic/newsapp/js/bootstrap.min.js' %}"></script>
  <!-- jquery, popper,bootstap.js CDN -->
  <script src="{% static 'adminstatic/newsapp/js/main.js' %}"></script>

  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> -->
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script> -->



  <!-- {# JQUERY FILE UPLOAD SCRIPTS #} -->
  <script src="{% static 'adminstatic/newsapp/js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'adminstatic/newsapp/js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'adminstatic/newsapp/js/jquery-file-upload/jquery.fileupload.js' %}"></script>
  <!-- {# PHOTOS PAGE SCRIPTS #} -->
  <script src="{% static 'adminstatic/newsapp/js/image-upload.js' %}"></script>
  
</body>

</html>

templates/admintemplates/adminlogin.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<div class="container mt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Log in</button>
    </form>

</div>
{% endblock content %}

templates/admintemplates/adminlogout.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<div class="container">
    <h2>You have been logout!</h2>
    <div class="border-top-3">
        <a href="{% url 'newsapp:adminlogin' %}"></a>
    </div>
</div>

{% endblock content %}

templates/admintemplates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <a class="navbar-brand" href="{% url 'newsapp:adminnewslist' %}">NewsApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'newsapp:adminnewslist' %}">Home
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <span>Hi {{ request.user|capfirst }}</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'newsapp:adminnewscreate' %}">Post Create</a>
                    <a class="dropdown-item" href="{% url 'newsapp:adminlogout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'newsapp:adminlogin' %}" class="nav-link">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/admintemplates/newsdetail.html
{% extends "admintemplates/adminbase.html" %}
{% block content %}
<div class="container">
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <p class="card-text"><small class="text-muted">Last updated {{ post.updated_at |date:"M d, Y"}} &nbsp; @{{ post.author }}</small></p>
    <p class="card-text">{{ post.content | safe }}</p>
    {% for tag in post.tag.all %}
    <span>#{{ tag }} &nbsp;</span> 
    {% endfor %}
  </div>
</div>
</div>
{% endblock content %}