api/urls.py
from django.urls import path, include
from .views import *
from newsapp.models import *
from rest_framework import routers




router = routers.DefaultRouter()


router.register('tag', TagAPIView)
router.register('category', CategoryAPIView)
router.register('topic', TopicAPIView)
router.register('news', NewsAPIView)





urlpatterns = [
   path('', include(router.urls)),
]

newsapp/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'newsapp'


urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('<int:pk>/detail/', ClientPostDetailView.as_view(), name='clientnewsdetail'),
    path('posts/topic/<int:pk>/', ClientPostTopic.as_view(), name='clientnewstopic'),
    path('posts/tag/<int:pk>/', ClientPostTag.as_view(), name='clientnewstag'),
    path('posts/category/<int:pk>/', ClientPostCategory.as_view(), name='clientnewscategory'),
    
    



    # CLIENT URL PATTERNS

    # path('', ClientHomeView.as_view(), name="clienthome"),
    # path('blogs/', ClientDemoView.as_view(), name="clientbloglist"),



    # ADMIN URL PATTERNS


    #  ADMIN AUTHENTICATION
    path('admin-login/', auth_views.LoginView.as_view(template_name='admintemplates/adminlogin.html'), name='adminlogin'),
    path('admin-logout/', auth_views.LogoutView.as_view(template_name='admintemplates/adminlogout.html'), name='adminlogout'),

    # ADMIN:NEWS CRUD
    path('admin-panel/news/',
         AdminNewsListView.as_view(),
         name='adminnewslist'),
    path('admin-panel/news/<int:pk>/detail/',
         AdminNewsDetailView.as_view(),
         name='adminnewsdetail'),
    path('admin-panel/news/create/',
         AdminNewsCreateView.as_view(),
         name='adminnewscreate'),
    path('admin-panel/news/<int:pk>/update/',
         AdminNewsUpdateView.as_view(),
         name='adminnewsupdate'),
    path('admin-panel/news/<int:pk>/delete/',
         AdminNewsDeleteView.as_view(),
         name='adminnewsdelete'),





    # path('album/create/', AdminGalleryCreateView.as_view(), name='adminalbumcreate'),
    

    path('album/create/', AdminGalleryView.as_view(), name='adminalbumcreate'),
#     path('album/delete/<int:pk>', AdminImageDeleteView.as_view(), name='adminalbumdelete'),
    path('album/delete/<int:pk>', adminDeleteImage, name='adminalbumdelete'),

    # path('album/<int:pk>/', AdminAlbumDetailView.as_view(), name='adminalbumlist'),


    # path('admin-panel/blog/create/',
    #      BlogCreateView.as_view(),
    #      name='adminblogcreate'),
    # path('admin-panel/blog/<int:pk>/update/',
    #      BlogUpdateView.as_view(),
    #      name='adminblogupdate'),
    # path('admin-panel/blog/<int:pk>/delete/',
    #      BlogDeleteView.as_view(),
    #      name='adminblogdelete'),

]

newsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from newsapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('summernote/', include('django_summernote.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Tag(models.Model):
    word = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     abstract = True

    def __str__(self):
        return self.word


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='topics')

    def __str__(self):
        return self.subject


class Post(models.Model):
    STATUS_CHOICES = (
        ('unpublished', 'Unpublished'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    tag = models.ManyToManyField(Tag)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/%Y/%m/%d', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    update_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='+')
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='unpublished')
    post_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at',)



def get_image_filename(instance, filename):
    id = instance.post.id
    return "post_images/%s" % (id)


class Photo(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='photos/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.url


# class Album(models.Model):
#     name = models.CharField(max_length=30)
#     description = models.TextField()
#     created_at = models.DateTimeField(auto_now=True)
    

# class Images(models.Model):
#     album = models.ForeignKey(Album, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to=get_image_filename, verbose_name='Image')

newsapp/forms.py
from django import forms
from .models import Post, Photo
from django_summernote.widgets import SummernoteWidget


class AdminLoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=1000)
    password = forms.CharField(widget=forms.PasswordInput)


class AdminNewsForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'tag', 'topic', 'image',
                  'content', 'status')
        widgets = {
            'content': SummernoteWidget(),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'required': True,
                'placeholder': 'Say something...'
            }),

        }

class AdminPhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file',)
            
# class AlbumForm(forms.ModelForm):
#     image = forms.ImageField(label='Image')    
#     class Meta:
#         model = Album
#         fields = ('name', 'description',)


# class ImageForm(forms.ModelForm):
#     image = forms.ImageField(label='Image')    
#     class Meta:
#         model = Images
#         fields = ('image', )

newsapp/views.py
from django.views.generic import *
from django.urls import reverse_lazy, reverse
from .models import Post, Tag, Photo
from .forms import AdminNewsForm
from django.contrib.auth.models import User
from .models import *
from django.shortcuts import render, get_object_or_404
from .forms import *
from django.views.generic.edit import FormView
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.template import RequestContext
from django.views import View
import json
from django.template.loader import render_to_string





class AdminNewsListView(ListView):
    model = Post
    template_name = 'admintemplates/newsapp/newslist.html'
    # context_object_name ='news'


class AdminNewsDetailView(DetailView):
    model = Post
    template_name = 'admintemplates/newsdetail.html'


class AdminNewsCreateView(CreateView):
    form_class = AdminNewsForm
    template_name = 'admintemplates/newsapp/newscreate.html'
    success_url = reverse_lazy('newsapp:adminnewslist')
    # form_class = modelformset_factory(
    #     models.Sample,
    #     fields=['name', 'collected', 'location'],
    #     extra=3
    # )


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['image'] = ImageForm
        # context['com'] = CommentForm
        return context

    def form_valid(self, form):
        user = self.request.user.id
        author = User.objects.get(id=user)
        form.instance.author = author
        form.instance.update_by = author
        return super().form_valid(form)


class AdminNewsUpdateView(UpdateView):
    model = Post
    form_class = AdminNewsForm
    success_url = reverse_lazy('newsapp:adminnewslist')
    template_name = 'admintemplates/newsapp/newsupdate.html'

    def form_valid(self, form):
        user = self.request.user.id
        author = User.objects.get(id=user)
        form.instance.author = author
        form.instance.update_by = author
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('newsapp:adminnewslist')


class AdminNewsDeleteView(DeleteView):
    model = Post

    def get_success_url(self):
        return reverse('newsapp:adminnewslist')


class ClientHomeView(ListView):
    template_name = 'clienttemplates/clienthome.html'
    model = Category
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super(ClientHomeView, self).get_context_data(**kwargs)
        context['popularposts'] = Post.objects.filter().order_by('-post_count')[:5]
        context['latest'] = Post.objects.filter().order_by('-created_at')[0:1]
        context['latests'] = Post.objects.filter().order_by('-created_at')[0:4]
        context['random'] = Post.objects.filter().order_by('?')[0:4]
        return context


class ClientPostDetailView(DetailView):
    template_name = 'clienttemplates/clientnewsdetail.html'
    model = Post

    # def get_queryset(self):
    #     self.post_count = get_object_or_404(Post, pk=self.kwargs['pk'])
    #     self.post_count = self.post_count.values('post_count') + 1
    #     return Post.objects.filter(topic=self.post_count)

    def get_context_data(self, **kwargs):
        context = super(ClientPostDetailView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        obj = self.get_object()
        obj.post_count += 1
        obj.save()
        return context


class ClientPostTopic(ListView):
    model = Post
    template_name = 'clienttemplates/clientnewstopic.html'
    paginate_by = 1

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, pk=self.kwargs['pk'])
        return Post.objects.filter(topic=self.topic)

    def get_context_data(self, **kwargs):
        context = super(ClientPostTopic, self).get_context_data(**kwargs)
        context['topic'] = self.topic
        context['categories'] = Category.objects.all()
        return context


class ClientPostTag(ListView):
    model = Post
    template_name = 'clienttemplates/clientnewstag.html'
    paginate_by = 1

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, pk=self.kwargs['pk'])
        return Post.objects.filter(tag=self.tag)

    def get_context_data(self, **kwargs):
        context = super(ClientPostTag, self).get_context_data(**kwargs)
        context['tag'] = self.tag
        context['categories'] = Category.objects.all()
        return context



class ClientPostCategory(ListView):
    model = Post
    template_name = 'clienttemplates/clientnewscategory.html'
    paginate_by = 2

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Post.objects.filter(topic__category=self.category)

    def get_context_data(self, **kwargs):
        context = super(ClientPostCategory, self).get_context_data(**kwargs)
        context['category'] = self.category
        context['categories'] = Category.objects.all()
        post__category = Category.objects.get(id=self.kwargs['pk']) #taking single category name
        context['cat'] = post__category
        return context


class AdminGalleryView(View):
    def get(self, request):
        photos_list = Photo.objects.all()
        return render(self.request, 'admintemplates/newsapp/albumcreate.html', {'photos': photos_list})

    def post(self, request):
        form = AdminPhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid() and request.is_ajax():
            photo = form.save()
            data = {
            'is_valid': True, 
            'name': photo.file.name,
            'url': photo.file.url,
            'id': photo.id,
            }
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def adminDeleteImage(request, pk):
    data = dict()
    photo = get_object_or_404(Photo,id=pk)
    if request.method == "POST" and request.is_ajax():
        photo.delete()
        data['form_is_valid'] = True
        photos = Photo.objects.all()
        data['photo_list'] = render_to_string('admintemplates/newsapp/albumcreate.html',{'photos':photos})
    else:
        context = {'photo':photo}
        data['html_form'] = render_to_string('admintemplates/newsapp/albumcreate.html',context,request=request)

    return JsonResponse(data)




# class AdminImageDeleteView(DeleteView):
#     model = Photo
#     template_name = "admintemplates/newsapp/albumcreate.html"
#     success_url = "/"

#     # allow delete only logged in user by appling decorator
#     # @method_decorator(login_required)
#     def dispatch(self, *args, **kwargs):
#         # maybe do some checks here for permissions ...

#         resp = super(AdminImageDeleteView, self).dispatch(*args, **kwargs)
#         if self.request.is_ajax():
#             response_data = {"result": "ok"}
#             return HttpResponse(json.dumps(response_data),
#                 content_type="application/json")
#         else:
#             # POST request (not ajax) will do a redirect to success_url
#             return resp


# class AdminImageDeleteView(DeleteView):
#     model = Photo


#     # def delete(self, request, *args, **kwargs):
#     #     self.get_object().delete()
#     #     payload = {'delete': 'ok'}
#     #     return HttpResponse(json.dumps(payload), mimetype='application/json')

#     def get_success_url(self):
#         return reverse('newsapp:adminalbumcreate')





# class AdminGalleryCreateView(FormView):
#     success_url = reverse_lazy('newsapp:adminalbumdetail')
#     template_name = 'admintemplates/adminalbumcreate.html'
#     form_class = ImageForm

#     # def get_form_kwargs(self):
#     #     kwargs = super(AdminGalleryCreateView, self).get_form_kwargs()
#     #     kwargs["queryset"] = Images.objects.none()
#     #     return kwargs

#     def form_valid(self, form):
#         user = self.request.user.id
#         author = User.objects.get(id=user)
#         form.instance.author = author
#         return super().form_valid(form)



# class AdminGalleryCreateView(FormView):
#     success_url = reverse_lazy('newsapp:adminalbumdetail')
#     form_class = modelformset_factory(
#         Images,
#         fields=['name', 'description', 'image'],
#         extra=3
#     )
#     template_name = 'admintemplates/adminalbumcreate.html'

#     def get_form_kwargs(self):
#         kwargs = super(AdminGalleryCreateView, self).get_form_kwargs()
#         kwargs["queryset"] = Images.objects.none()
#         return kwargs

#     def form_valid(self, form):
#         for sub_form in form:
#             if sub_form.has_changed():
#                 sub_form.save()

#         return super(AdminGalleryCreateView, self).form_valid(form)



# def album(request):

#     ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=3)

#     if request.method == 'POST':

#         postForm = AlbumForm(request.POST)
#         formset = ImageFormSet(request.POST, request.FILES, queryset=Images.objects.none())

#         if postForm.is_valid() and formset.is_valid():
#             post_form = postForm.save(commit=False)
#             post_form.user = request.user
#             post_form.save()

#             for form in formset.cleaned_data:
#                 image = form['image']
#                 photo = Images(post=post_form, image=image)
#                 photo.save()
#             messages.success(request, "Posted!")
#             return HttpResponseRedirect("/")
#         else:
#             print (postForm.errors, formset.errors)
#     else:
#         postForm = AlbumForm()
#         formset = ImageFormSet(queryset=Images.objects.none())
#     return render(request, 'admintemplates/newsapp/albumcreate.html',
#                   {
#                   'postForm': postForm, 
#                   'formset': formset},

templates/admintemplates/newsapp/albumcreate.html
{% extends "admintemplates/adminbase.html" %}

{% block content %}

{% block section %}
<!-- {# 1. BUTTON TO TRIGGER THE ACTION #} -->
<button type="button" class="btn btn-primary js-upload-photos">
    <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
</button>

<!-- {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #} -->
<input id="fileupload" type="file" name="file" multiple style="display: none;"
    data-url="{% url 'newsapp:adminalbumcreate' %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

<!-- {# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #} -->
<div class="table border">
<table id="gallery">
  <h2>Photos</h2>

    <tbody>
        {% for photo in photos %}
        <tr id="row{{photo.pk}}"> 
            <td>
            	<a href="{{ photo.file.url }}">
            		<img src="{{photo.file.url}}" class="img-thumbnail"  alt="{{photo.file.name}}" width="200" height="200"> {{ photo.file.name }} || {{ photo.id }}
            	</a>
            </td>
            
            <td>
              <button class="ramesh btn btn-danger" photo-id="{{ photo.pk }}" onclick="del({{ photo.pk }})" style="margin:80px;">Delete {{ photo.pk }}</button>
            </td>

        </tr>

       

        {% endfor %}
    </tbody>
</table>
</div>
{% endblock section %}

{% endblock %}

templates/admintemplates/newsapp/newscreate.html
{% extends "admintemplates/adminbase.html" %}
{% block content %}
<style>
	#id_tag {
    height: 50px ;
    width: 500px;
}
</style>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<div class="container">
<h1>Create News</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p}}
    <input class="btn btn-success" type="submit" value="Post">
</form>
</div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script>
	$(document).ready(function() {
    $('#id_tag').select2({
    	tags: true,
    tokenSeparators: [',', ' ']
    });

});
</script>
{% endblock content %}

templates/admintemplates/newsapp/newslist.html
{% extends "admintemplates/adminbase.html" %}
{% block content %}
<div class="container">
    <h2>News List</h2>
    <div class="create mr-left">
        <a class="btn btn-primary" href="{% url 'newsapp:adminnewscreate' %}" role="button">Create News</a>
    </div><br>
    <hr>

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for news.." title="Type in a name">

    <table id="myTable">
        <tr class="header">
            <th class="alert alert-primary" style="width:40%;">Title</th>
            <th class="alert alert-success" style="width:20%;">Pub_Date</th>
            <th class="alert alert-secondary" style="width:10%;">Author</th>
            <th class="alert alert-warning" style="width:10%;">Status</th>
            <th class="alert alert-danger" style="width:20%;">Operation</th>
        </tr>{% for news in object_list %}
        <tr>
            <td><a href="{% url 'newsapp:adminnewsdetail' news.pk %}" class="alert-link">{{ news.title }}</a></td>
            <td>{{ news.created_at | date:"M d, Y"}}</td>
            <td>{{ news.author }}</td>
            <td>{{ news.status }}</td>
            <td>
                <a class="btn btn-success" href="{% url 'newsapp:adminnewsupdate'  news.pk %}" role="button">Update</a>

                <button type="button" class="btn btn-danger" data-toggle="modal"
                    data-target="#exampleModal">Delete</button>
            </td>

        </tr>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'newsapp:adminnewsdelete' news.pk %}" method="post">{% csrf_token %}
                            <p>Are your sure to delete </p>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <input class="btn btn-danger" type="submit" value="Confirm">
                        </form>
                    </div>

                </div>
            </div>
        </div>
        {% endfor %}
    </table>

</div>

{% endblock content %}

templates/admintemplates/newsapp/newsupdate.html
{% extends "admintemplates/adminbase.html" %}
{% block content %}
<div class="container">
    <h1>Edit Post</h1>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="Update">
    </form>
</div>
{% endblock content %}